### ISSUE TITLE
Add option to show temperature in fahrenheit?

### ISSUE THREAD

**Issue by vinh291** [Toolbench/Tupiq#5]

**Comment by ghjunior** [comment]
Hey @vinh291, yup we'll work that in. I'll update the ticket once it's up.

**Comment by ghjunior** [comment]
[The commit for this is up here](https://github.com/Toolbench/Tupiq/commit/0f67ac007cd408f4879a4bd392f747c4bd7d4e3c). I'm reviewing and testing that all is good and will update the extension soon.

**Comment by ghjunior** [comment]
Hey @vinh291, this has been added to [v1.2.0](https://github.com/Toolbench/Tupiq/releases/tag/v1.2.0). You might have to manually update the extension since there is a new permission requirement (in order to save the settings). To do this visit this page `chrome://extensions`, click on the "Update extensions now" button, and re-enable the extension. Thanks for the feedback!
